// -------------------------------------------------------------
// 
// File Name: D:\slsf_randgen\slsf\reportsneo\2024-01-29-11-29-59\Verilog_hdlsrc\sampleModel1641_sub\cfblk11.v
// Created: 2024-01-30 08:53:27
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk11
// Source Path: sampleModel1641_sub/Subsystem/cfblk11
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk11
          (u,
           y);


  input   [7:0] u;  // uint8
  output  [7:0] y;  // uint8


  wire [7:0] Lower_Limit_out1;  // uint8
  wire Lower_Test_relop1;
  wire [7:0] Upper_Limit_out1;  // uint8
  wire Upper_Test_relop1;
  wire AND_bool;
  wire [7:0] AND_out1;  // uint8


  assign Lower_Limit_out1 = 8'b00000000;



  assign Lower_Test_relop1 = Lower_Limit_out1 <= u;



  assign Upper_Limit_out1 = 8'b00000001;



  assign Upper_Test_relop1 = u <= Upper_Limit_out1;



  assign AND_bool = Lower_Test_relop1 & Upper_Test_relop1;



  assign AND_out1 = {7'b0, AND_bool};



  assign y = AND_out1;

endmodule  // cfblk11

