// -------------------------------------------------------------
// 
// File Name: D:\slsf_randgen\slsf\reportsneo\2024-01-29-11-29-59\Verilog_hdlsrc\sampleModel1641_sub\cfblk192.v
// Created: 2024-01-30 08:53:27
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk192
// Source Path: sampleModel1641_sub/Subsystem/cfblk192
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk192
          (In1,
           Out1);


  input   [3:0] In1;  // ufix4_E4
  output  [3:0] Out1;  // ufix4_E4




  assign Out1 = In1;

endmodule  // cfblk192

