// -------------------------------------------------------------
// 
// File Name: D:\slsf_randgen\slsf\reportsneo\2024-01-29-11-29-59\Verilog_hdlsrc\sampleModel1641_sub\cfblk189.v
// Created: 2024-01-30 08:53:27
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk189
// Source Path: sampleModel1641_sub/Subsystem/cfblk189
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk189
          (In1,
           Out1);


  input   [15:0] In1;  // uint16
  output  [15:0] Out1;  // uint16




  assign Out1 = In1;

endmodule  // cfblk189

