// -------------------------------------------------------------
// 
// File Name: D:\slsf_randgen\slsf\reportsneo\2024-01-29-11-29-59\Verilog_hdlsrc\sampleModel1641_sub\Subsystem_tb.v
// Created: 2024-01-30 08:53:29
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_tb
// Source Path: 
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns



module Subsystem_tb;



  reg  clk;
  reg  reset;
  wire clk_enable;
  wire Hdl_out_done;  // ufix1
  wire rdEnb;
  wire Hdl_out_done_enb;  // ufix1
  reg [3:0] cfblk180_addr;  // ufix4
  wire Hdl_out_lastAddr;  // ufix1
  wire resetn;
  reg  check4_done;  // ufix1
  wire cfblk182_done;  // ufix1
  wire cfblk182_done_enb;  // ufix1
  wire cfblk182_lastAddr;  // ufix1
  reg  check3_done;  // ufix1
  wire cfblk181_done;  // ufix1
  wire cfblk181_done_enb;  // ufix1
  wire cfblk181_lastAddr;  // ufix1
  reg  check2_done;  // ufix1
  wire cfblk180_done;  // ufix1
  wire cfblk180_done_enb;  // ufix1
  wire cfblk180_active;  // ufix1
  wire snkDone;
  wire snkDonen;
  wire tb_enb;
  reg  tb_enb_delay;
  wire ce_out;
  wire [7:0] cfblk180;  // uint8
  wire [7:0] cfblk181;  // uint8
  wire [7:0] cfblk182;  // uint8
  wire [7:0] Hdl_out;  // uint8
  wire cfblk180_enb;  // ufix1
  wire cfblk180_lastAddr;  // ufix1
  reg  check1_done;  // ufix1
  wire [7:0] cfblk180_expected_1;  // uint8
  wire [7:0] cfblk180_ref;  // uint8
  reg  cfblk180_testFailure;  // ufix1
  wire [7:0] cfblk181_expected_table_data [0:10];  // ufix8 [11]
  wire [7:0] cfblk181_expected_1;  // ufix8
  wire [7:0] cfblk181_expected_2;  // uint8
  wire [7:0] cfblk181_ref;  // uint8
  reg  cfblk181_testFailure;  // ufix1
  wire [7:0] cfblk182_expected_1;  // uint8
  wire [7:0] cfblk182_ref;  // uint8
  reg  cfblk182_testFailure;  // ufix1
  wire [7:0] Hdl_out_expected_table_data [0:10];  // ufix8 [11]
  wire [7:0] Hdl_out_expected_1;  // ufix8
  wire [7:0] Hdl_out_expected_2;  // uint8
  wire [7:0] Hdl_out_ref;  // uint8
  reg  Hdl_out_testFailure;  // ufix1
  wire testFailure;  // ufix1


  assign Hdl_out_done_enb = Hdl_out_done & rdEnb;



  assign Hdl_out_lastAddr = cfblk180_addr >= 4'b1010;



  assign Hdl_out_done = Hdl_out_lastAddr & resetn;



  // Delay to allow last sim cycle to complete
  always @(posedge clk or posedge reset)
    begin : checkDone_4
      if (reset) begin
        check4_done <= 0;
      end
      else begin
        if (Hdl_out_done_enb) begin
          check4_done <= Hdl_out_done;
        end
      end
    end

  assign cfblk182_done_enb = cfblk182_done & rdEnb;



  assign cfblk182_lastAddr = cfblk180_addr >= 4'b1010;



  assign cfblk182_done = cfblk182_lastAddr & resetn;



  // Delay to allow last sim cycle to complete
  always @(posedge clk or posedge reset)
    begin : checkDone_3
      if (reset) begin
        check3_done <= 0;
      end
      else begin
        if (cfblk182_done_enb) begin
          check3_done <= cfblk182_done;
        end
      end
    end

  assign cfblk181_done_enb = cfblk181_done & rdEnb;



  assign cfblk181_lastAddr = cfblk180_addr >= 4'b1010;



  assign cfblk181_done = cfblk181_lastAddr & resetn;



  // Delay to allow last sim cycle to complete
  always @(posedge clk or posedge reset)
    begin : checkDone_2
      if (reset) begin
        check2_done <= 0;
      end
      else begin
        if (cfblk181_done_enb) begin
          check2_done <= cfblk181_done;
        end
      end
    end

  assign cfblk180_done_enb = cfblk180_done & rdEnb;



  assign cfblk180_active = cfblk180_addr != 4'b1010;



  assign snkDonen =  ~ snkDone;



  assign resetn =  ~ reset;



  assign tb_enb = resetn & snkDonen;



  // Delay inside enable generation: register depth 1
  always @(posedge clk or posedge reset)
    begin : u_enable_delay
      if (reset) begin
        tb_enb_delay <= 0;
      end
      else begin
        tb_enb_delay <= tb_enb;
      end
    end

  assign rdEnb = (snkDone == 1'b0 ? tb_enb_delay :
              1'b0);



  assign #2 clk_enable = rdEnb;

  initial
    begin : reset_gen
      reset <= 1'b1;
      # (20);
      @ (posedge clk)
      # (2);
      reset <= 1'b0;
    end

  always 
    begin : clk_gen
      clk <= 1'b1;
      # (5);
      clk <= 1'b0;
      # (5);
      if (snkDone == 1'b1) begin
        clk <= 1'b1;
        # (5);
        clk <= 1'b0;
        # (5);
        $stop;
      end
    end

  Subsystem u_Subsystem (.clk(clk),
                         .reset(reset),
                         .clk_enable(clk_enable),
                         .ce_out(ce_out),
                         .cfblk180(cfblk180),  // uint8
                         .cfblk181(cfblk181),  // uint8
                         .cfblk182(cfblk182),  // uint8
                         .Hdl_out(Hdl_out)  // uint8
                         );

  assign cfblk180_enb = ce_out & cfblk180_active;



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 10
  always @(posedge clk or posedge reset)
    begin : c_2_process
      if (reset == 1'b1) begin
        cfblk180_addr <= 4'b0000;
      end
      else begin
        if (cfblk180_enb) begin
          if (cfblk180_addr >= 4'b1010) begin
            cfblk180_addr <= 4'b0000;
          end
          else begin
            cfblk180_addr <= cfblk180_addr + 4'b0001;
          end
        end
      end
    end



  assign cfblk180_lastAddr = cfblk180_addr >= 4'b1010;



  assign cfblk180_done = cfblk180_lastAddr & resetn;



  // Delay to allow last sim cycle to complete
  always @(posedge clk or posedge reset)
    begin : checkDone_1
      if (reset) begin
        check1_done <= 0;
      end
      else begin
        if (cfblk180_done_enb) begin
          check1_done <= cfblk180_done;
        end
      end
    end

  assign snkDone = check4_done & (check3_done & (check1_done & check2_done));



  // Data source for cfblk180_expected
  assign cfblk180_expected_1 = 8'b00000001;



  assign cfblk180_ref = cfblk180_expected_1;

  always @(posedge clk or posedge reset)
    begin : cfblk180_checker
      if (reset == 1'b1) begin
        cfblk180_testFailure <= 1'b0;
      end
      else begin
        if (ce_out == 1'b1 && cfblk180 !== cfblk180_ref) begin
          cfblk180_testFailure <= 1'b1;
          $display("ERROR in cfblk180 at time %t : Expected '%h' Actual '%h'", $time, cfblk180_ref, cfblk180);
        end
      end
    end

  // Data source for cfblk181_expected
  assign cfblk181_expected_table_data[0] = 8'b00000000;
  assign cfblk181_expected_table_data[1] = 8'b00000001;
  assign cfblk181_expected_table_data[2] = 8'b00000000;
  assign cfblk181_expected_table_data[3] = 8'b00000000;
  assign cfblk181_expected_table_data[4] = 8'b00000000;
  assign cfblk181_expected_table_data[5] = 8'b00000000;
  assign cfblk181_expected_table_data[6] = 8'b00000000;
  assign cfblk181_expected_table_data[7] = 8'b00000000;
  assign cfblk181_expected_table_data[8] = 8'b00000000;
  assign cfblk181_expected_table_data[9] = 8'b00000000;
  assign cfblk181_expected_table_data[10] = 8'b00000000;
  assign cfblk181_expected_1 = cfblk181_expected_table_data[cfblk180_addr];



  assign cfblk181_expected_2 = cfblk181_expected_1;



  assign cfblk181_ref = cfblk181_expected_2;

  always @(posedge clk or posedge reset)
    begin : cfblk181_checker
      if (reset == 1'b1) begin
        cfblk181_testFailure <= 1'b0;
      end
      else begin
        if (ce_out == 1'b1 && cfblk181 !== cfblk181_ref) begin
          cfblk181_testFailure <= 1'b1;
          $display("ERROR in cfblk181 at time %t : Expected '%h' Actual '%h'", $time, cfblk181_ref, cfblk181);
        end
      end
    end

  // Data source for cfblk182_expected
  assign cfblk182_expected_1 = 8'b00000000;



  assign cfblk182_ref = cfblk182_expected_1;

  always @(posedge clk or posedge reset)
    begin : cfblk182_checker
      if (reset == 1'b1) begin
        cfblk182_testFailure <= 1'b0;
      end
      else begin
        if (ce_out == 1'b1 && cfblk182 !== cfblk182_ref) begin
          cfblk182_testFailure <= 1'b1;
          $display("ERROR in cfblk182 at time %t : Expected '%h' Actual '%h'", $time, cfblk182_ref, cfblk182);
        end
      end
    end

  // Data source for Hdl_out_expected
  assign Hdl_out_expected_table_data[0] = 8'b00000000;
  assign Hdl_out_expected_table_data[1] = 8'b00000000;
  assign Hdl_out_expected_table_data[2] = 8'b00000010;
  assign Hdl_out_expected_table_data[3] = 8'b00000011;
  assign Hdl_out_expected_table_data[4] = 8'b00000010;
  assign Hdl_out_expected_table_data[5] = 8'b00000010;
  assign Hdl_out_expected_table_data[6] = 8'b00000010;
  assign Hdl_out_expected_table_data[7] = 8'b00000010;
  assign Hdl_out_expected_table_data[8] = 8'b00000010;
  assign Hdl_out_expected_table_data[9] = 8'b00000010;
  assign Hdl_out_expected_table_data[10] = 8'b00000010;
  assign Hdl_out_expected_1 = Hdl_out_expected_table_data[cfblk180_addr];



  assign Hdl_out_expected_2 = Hdl_out_expected_1;



  assign Hdl_out_ref = Hdl_out_expected_2;

  always @(posedge clk or posedge reset)
    begin : Hdl_out_checker
      if (reset == 1'b1) begin
        Hdl_out_testFailure <= 1'b0;
      end
      else begin
        if (ce_out == 1'b1 && Hdl_out !== Hdl_out_ref) begin
          Hdl_out_testFailure <= 1'b1;
          $display("ERROR in Hdl_out at time %t : Expected '%h' Actual '%h'", $time, Hdl_out_ref, Hdl_out);
        end
      end
    end

  assign testFailure = Hdl_out_testFailure | (cfblk182_testFailure | (cfblk180_testFailure | cfblk181_testFailure));



  always @(posedge clk)
    begin : completed_msg
      if (snkDone == 1'b1) begin
        if (testFailure == 1'b0) begin
          $display("**************TEST COMPLETED (PASSED)**************");
        end
        else begin
          $display("**************TEST COMPLETED (FAILED)**************");
        end
      end
    end

endmodule  // Subsystem_tb

